### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'FontDiffuser/ckpt/unet.pth'

### ISSUE THREAD

**Issue by BeiZhai-WangYu** [guanhaisu/OBSD#3]
hello, how can i get the 'FontDiffuser/ckpt/unet.pth'

**Comment by guanhaisu** [comment]
You can find the model weights here, https://drive.google.com/drive/folders/1kRwi5sfHn6oufydDmd-7X9pPFDZzFjkk?usp=drive_link. Or you can get it directly from the FontDiffuser project, https://github.com/yeungchenwa/FontDiffuser.

**Comment by BeiZhai-WangYu** [comment]
thanks!
