### ISSUE TITLE
你好，我用64size训练，为什么验证只出来一个字的一部分，这明显和论文的结果不符合啊？？

### ISSUE THREAD

**Issue by fany4311** [guanhaisu/OBSD#4]

**Comment by 1141294144** [comment]
可不可以说一下你复现的时候数据集是怎么处理的？

**Comment by 1141294144** [comment]
> _No description provided._

可不可以说一下你复现的时候数据集是怎么处理的？很期待你的回复

**Comment by fany4311** [comment]
我是按照论文来的，但是最后结果效果其实不是很好，可能是我训练有问题？？他很多字都翻译不过来
