### ISSUE TITLE
你好，1.我用64size训练，为什么验证只出来一个字的一部分，这明显和论文的结果不符合啊？？

### ISSUE THREAD

**Issue by fany4311** [guanhaisu/OBSD#5]

**Comment by fany4311** [comment]
第二个问题2.验证集是怎么定义的，是甲骨文中不拿去训练的的一部分嘛。
感谢解答，谢谢！

**Comment by fany4311** [comment]
![image](https://github.com/user-attachments/assets/cf70ab3d-a081-4d32-b087-9cde26ebcdd2)

**Comment by guanhaisu** [comment]
64size是因为训练的时候会把图像进行patch切块，所以只有整张图像的一部分，每个patch是64×64大小，在推理的时候会利用滑动窗口进行多个patch的融合。验证集这里没有明确的定义，代码里的逻辑是抽取训练集中的一些图像进行某个局部patch的推理并保存推理结果，所以你看到的验证结果只是图像中的一个局部区域。如果要推理完整的图像，需要使用提供的测试代码进行图像生成。

**Comment by fany4311** [comment]
谢谢

**Comment by 1141294144** [comment]
> 谢谢

可不可以说一下你复现的时候数据集是怎么处理的？
